version: '3.8'

services:
  wordpress:
    image: 'wordpress:latest'
    volumes:
      - 'wordpress-files:/var/www/html'
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=${WP_DB_USER:-wp_default_user}
      - WORDPRESS_DB_PASSWORD=${WP_DB_PASSWORD:-wp_default_pass}
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_CONFIG_EXTRA=define('WP_HOME', 'https://' . $_SERVER['HTTP_HOST']); define('WP_SITEURL', 'https://' . $_SERVER['HTTP_HOST']);
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1"]
      interval: 2s
      timeout: 10s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 2048M
        reservations:
          memory: 512M

  mysql:
    image: 'mysql:8'
    volumes:
      - 'mysql-data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=${WP_DB_ROOT_PASSWORD:-root_default_pass}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=${WP_DB_USER:-wp_default_user}
      - MYSQL_PASSWORD=${WP_DB_PASSWORD:-wp_default_pass}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 5s
      timeout: 20s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 1024M
        reservations:
          memory: 256M

volumes:
  wordpress-files:
  mysql-data:
