version: '3.8'

services:
  phpmyadmin_central:
    image: phpmyadmin:latest
    container_name: hostinlink-pma-git # Nombre fijo para controlarlo
    environment:
      - PMA_ARBITRARY=1 # Te permite escribir el host manualmente
    #networks:
    #  - bunker-coolify

#networks:
#  bunker-coolify:
#    name: coolify # El ID exacto de tu red predefinida
#    external: true # Le prohíbe a Docker crear una red nueva aislada
